[tool.pycln]
all = true
skip_imports = [
  # Modules with known side-effects
  "coloreditor", # Adds doc template
  "IDLEenvironment", # Injects fast_readline into the IDLE auto-indent extension
  "pythoncom", # pythoncomXX.dll loader
  "pywintypes", # pywintypesXX.dll loader
  "win32com", # Sets pythoncom.frozen and adds modules to path based on the registry
  "win32traceutil", # Redirects output to win32trace remote collector
  "win32ui", # Must always be imported before dde
]
# Note: com/win32com/client/gencache.py does read files but only to fill in it's own dicts from cache
