[tool.pycln]
# Many imports with side-effects
all = false
skip_imports = [
  # Star imported C wrapped modules
  "_winxptheme",
  "dde",
  "ntsecuritycon",
  "odbc",
  "win32api",
  "win32clipboard",
  "win32com",
  "win32cryptcon",
  "win32event",
  "win32file",
  "win32gui_struct",
  "win32gui",
  "win32inet",
  "win32inetcon",
  "win32pipe",
  "win32ras",
  "win32ui",
]
