// This file declares the IBrowserFrameOptions Interface and Gateway for Python.
// Generated by makegw.py
// ---------------------------------------------------
//
// Interface Declaration

class PyIBrowserFrameOptions : public PyIUnknown
{
public:
	MAKE_PYCOM_CTOR(PyIBrowserFrameOptions);
	static IBrowserFrameOptions *GetI(PyObject *self);
	static PyComTypeObject type;

	// The Python methods
	static PyObject *GetFrameOptions(PyObject *self, PyObject *args);

protected:
	PyIBrowserFrameOptions(IUnknown *pdisp);
	~PyIBrowserFrameOptions();
};
// ---------------------------------------------------
//
// Gateway Declaration

class PyGBrowserFrameOptions : public PyGatewayBase, public IBrowserFrameOptions
{
protected:
	PyGBrowserFrameOptions(PyObject *instance) : PyGatewayBase(instance) { ; }
	PYGATEWAY_MAKE_SUPPORT2(PyGBrowserFrameOptions, IBrowserFrameOptions, IID_IBrowserFrameOptions, PyGatewayBase)



	// IBrowserFrameOptions
	STDMETHOD(GetFrameOptions)(
		BROWSERFRAMEOPTIONS dwMask,
		BROWSERFRAMEOPTIONS * pdwOptions);

};
