blank_issues_enabled: false
contact_links:
  - name: Typeshed type stubs and annotations
    url: https://github.com/python/typeshed/issues?q=state%3Aopen+pywin32
    about: For static type-checking and IntelliSense
  - name: python-win32 mailing list
    url: http://mail.python.org/mailman/listinfo/python-win32
    about: For support requests, problems or questions
