// This file declares the IPropertySetStorage Interface and Gateway for Python.
// Generated by makegw.py
// ---------------------------------------------------
//
// Interface Declaration

class PyIPropertySetStorage : public PyIUnknown
{
public:
	MAKE_PYCOM_CTOR(PyIPropertySetStorage);
	static IPropertySetStorage *GetI(PyObject *self);
	static PyComEnumProviderTypeObject type;

	// The Python methods
	static PyObject *Create(PyObject *self, PyObject *args);
	static PyObject *Open(PyObject *self, PyObject *args);
	static PyObject *Delete(PyObject *self, PyObject *args);
	static PyObject *Enum(PyObject *self, PyObject *args);
protected:
	PyIPropertySetStorage(IUnknown *pdisp);
	~PyIPropertySetStorage();
};
