

#define DB_PEGOID_CREATED              DB_CEOID_CREATED
#define DB_PEGOID_RECORD_DELETED       DB_CEOID_RECORD_DELETED
#define DB_PEGOID_CHANGED	           DB_CEOID_CHANGED
#define PEGPROPID                      CEPROPID
#define PPEGPROPID                     PCEPROPID
#define PEGOID                         CEOID
#define PPEGOID                        PCEOID
#define PEGFILEINFO                    CEFILEINFO
#define PEGDIRINFO                     CEDIRINFO
#define PEGRECORDINFO                  CERECORDINFO
#define PEGDB_SORT_DESCENDING          CEDB_SORT_DESCENDING
#define PEGDB_SORT_CASEINSENSITIVE     CEDB_SORT_CASEINSENSITIVE
#define PEGDB_SORT_UNKNOWNFIRST        CEDB_SORT_UNKNOWNFIRST
#define PEGDB_SORT_GENERICORDER        CEDB_SORT_GENERICORDER
#define PEGDB_MAXDBASENAMELEN          CEDB_MAXDBASENAMELEN
#define PEGDB_MAXSORTORDER             CEDB_MAXSORTORDER
#define PEGDB_VALIDNAME                CEDB_VALIDNAME
#define PEGDB_VALIDTYPE                CEDB_VALIDTYPE
#define PEGDB_VALIDSORTSPEC            CEDB_VALIDSORTSPEC
#define PEGDB_VALIDMODTIME	           CEDB_VALIDMODTIME
#define PEGDBASEINFO                   CEDBASEINFO
#define PEGOIDINFO                     CEOIDINFO
#define PEGDB_AUTOINCREMENT            CEDB_AUTOINCREMENT
#define PEGDB_SEEK_PEGOID              CEDB_SEEK_CEOID
#define PEGDB_SEEK_BEGINNING           CEDB_SEEK_BEGINNING
#define PEGDB_SEEK_END                 CEDB_SEEK_END
#define PEGDB_SEEK_CURRENT             CEDB_SEEK_CURRENT
#define PEGDB_SEEK_VALUESMALLER        CEDB_SEEK_VALUESMALLER
#define PEGDB_SEEK_VALUEFIRSTEQUAL     CEDB_SEEK_VALUEFIRSTEQUAL
#define PEGDB_SEEK_VALUEGREATER        CEDB_SEEK_VALUEGREATER
#define PEGDB_SEEK_VALUENEXTEQUAL      CEDB_SEEK_VALUENEXTEQUAL
#define PEGBLOB                        CEBLOB
#define PEGVT_I2                       CEVT_I2
#define PEGVT_UI2                      CEVT_UI2
#define PEGVT_I4                       CEVT_I4
#define PEGVT_UI4                      CEVT_UI4
#define PEGVT_FILETIME                 CEVT_FILETIME
#define PEGVT_LPWSTR                   CEVT_LPWSTR
#define PEGVT_BLOB                     CEVT_BLOB
#define PEGVALUNION                    CEVALUNION
#define PEGDB_PROPNOTFOUND             CEDB_PROPNOTFOUND
#define PEGDB_PROPDELETE               CEDB_PROPDELETE
#define PEGPROPVAL                     CEPROPVAL
#define PPEGPROPVAL                    PCEPROPVAL
#define PEGDB_MAXDATABLOCKSIZE         CEDB_MAXDATABLOCKSIZE
#define PEGDB_MAXPROPDATASIZE          CEDB_MAXPROPDATASIZE
#define PEGDB_MAXRECORDSIZE            CEDB_MAXRECORDSIZE
#define PEGDB_ALLOWREALLOC             CEDB_ALLOWREALLOC
#define PegOidGetInfo                  CeOidGetInfo
#define PegFindFirstDatabase           CeFindFirstDatabase
#define PegFindNextDatabase            CeFindNextDatabase
#define PegCreateDatabase              CeCreateDatabase
#define PegSetDatabaseInfo             CeSetDatabaseInfo
#define PegOpenDatabase                CeOpenDatabase
#define PegDeleteDatabase              CeDeleteDatabase
#define PegSeekDatabase                CeSeekDatabase
#define PegDeleteRecord                CeDeleteRecord
#define PegReadRecordProps             CeReadRecordProps
#define PegWriteRecordProps            CeWriteRecordProps


