name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: 'This is a stale issue and will be closed in 5 days'
          stale-pr-message: 'This is a stale pull request and will be closed in 5 days'
          days-before-stale: 30
          days-before-close: 5
