name: main

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 }]
    steps:

      - uses: actions/checkout@v2
        with:
          path: temp
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel mingw-w64-${{ matrix.arch }}-toolchain
          update: true

      - name: Build package
        run: python setup.py --skip-verstamp build

      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse
      - name: CI-Build
        shell: msys2 {0}
        run: |
          cd /C/_
          MINGW_INSTALLS=${{ matrix.msystem }} ./ci-build.sh
      - name: "Upload binaries"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.msystem }}-packages
          path: C:/_/artifacts/*.pkg.tar.*

      - name: "Upload sources"
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: C:/_/artifacts/*.src.tar.*

